python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer1.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer2.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer3.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer4.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer5.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer6.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer7.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer8.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer9.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer10.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer11.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer12.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer13.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer14.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer15.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer16.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer17.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer18.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer19.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer20.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer21.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer22.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer23.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer24.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer25.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer26.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer27.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer28.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer29.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer30.json

python3 scripts/analysis/interactive_nearest_neighbors_viewer.py --results-file analysis_results/nearest_neighbors/train_mlp-only_pixmo_cap_resize_olmo-7b_vit-l-14-336_seed10_step12000-unsharded/nearest_neighbors_analysis_pixmo_cap_multi-gpu_layer31.json