#!/usr/bin/env python3
"""
Create Qwen2-VL plots.

Generates plots for the off-the-shelf Qwen2-VL-7B-Instruct model.
"""

import json
import argparse
from pathlib import Path
import matplotlib
matplotlib.use('Agg')
import matplotlib.pyplot as plt
import seaborn as sns

# Paths
SCRIPT_DIR = Path(__file__).parent
DATA_JSON = SCRIPT_DIR / "data.json"
OUTPUT_DIR = SCRIPT_DIR / "paper_figures_output" / "qwen2vl"


def load_data():
    """Load data from data.json."""
    with open(DATA_JSON, 'r') as f:
        return json.load(f)


def create_unified_plot(nn_data, logitlens_data, contextual_data):
    """Create unified plot with all three methods."""
    fig, axes = plt.subplots(1, 3, figsize=(18, 5))
    sns.set_style("whitegrid")

    configs = [
        (axes[0], nn_data, '(a) Static V-Lens (NN)', 'tab:blue'),
        (axes[1], logitlens_data, '(b) Logit Lens', 'tab:orange'),
        (axes[2], contextual_data, '(c) Contextual V-Lens', 'tab:green')
    ]

    for ax, data, title, color in configs:
        if data:
            layers = sorted(data.keys())
            values = [data[l] for l in layers]
            ax.plot(layers, values, marker='o', color=color, linewidth=3,
                   markersize=10, label='Qwen2-VL-7B')

        ax.set_xlabel('Layer', fontsize=14, fontweight='bold')
        ax.set_ylabel('Interpretability %', fontsize=14, fontweight='bold')
        ax.set_title(title, fontsize=16, fontweight='bold', pad=10)
        ax.grid(True, alpha=0.3)
        ax.set_ylim(0, 100)
        ax.tick_params(labelsize=11)
        if data:
            ax.set_xlim(min(layers) - 0.5, max(layers) + 0.5)
            ax.legend(fontsize=12)

    plt.tight_layout()
    return fig


def create_individual_plots(nn_data, logitlens_data, contextual_data):
    """Create individual plots for each method."""
    figs = {}

    methods = {
        'nn': ('Static V-Lens (NN)', nn_data, 'tab:blue'),
        'logitlens': ('Logit Lens', logitlens_data, 'tab:orange'),
        'contextual': ('Contextual V-Lens', contextual_data, 'tab:green')
    }

    for method_key, (method_name, data, color) in methods.items():
        if not data:
            continue

        fig, ax = plt.subplots(figsize=(10, 6))
        sns.set_style("whitegrid")

        layers = sorted(data.keys())
        values = [data[l] for l in layers]
        ax.plot(layers, values, marker='o', color=color, linewidth=3,
               markersize=12, label='Qwen2-VL-7B-Instruct')

        ax.set_xlabel('Layer', fontsize=14, fontweight='bold')
        ax.set_ylabel('Interpretability %', fontsize=14, fontweight='bold')
        ax.set_title(f'Qwen2-VL: {method_name}', fontsize=16, fontweight='bold', pad=12)
        ax.grid(True, alpha=0.3)
        ax.set_ylim(0, 100)
        ax.set_xlim(min(layers) - 0.5, max(layers) + 0.5)
        ax.tick_params(labelsize=12)
        ax.legend(fontsize=13, framealpha=0.95)

        plt.tight_layout()
        figs[method_key] = fig

    return figs


def main():
    parser = argparse.ArgumentParser(description='Generate Qwen2-VL plots')
    parser.add_argument('--unified-only', action='store_true', help='Only generate unified plot')
    parser.add_argument('--individual-only', action='store_true', help='Only generate individual plots')
    args = parser.parse_args()

    # Load data
    print("Loading data from data.json...")
    data = load_data()

    if 'qwen2vl' not in data:
        print("ERROR: No qwen2vl data in data.json")
        print("Run: python update_data.py")
        return

    qwen2vl = data['qwen2vl']
    # Convert string keys to int (JSON stores all keys as strings)
    nn_data = {int(k): v for k, v in qwen2vl.get('nn', {}).items()}
    logitlens_data = {int(k): v for k, v in qwen2vl.get('logitlens', {}).items()}
    contextual_data = {int(k): v for k, v in qwen2vl.get('contextual', {}).items()}

    print(f"Found Qwen2-VL data:")
    print(f"  NN: {len(nn_data)} layers")
    print(f"  LogitLens: {len(logitlens_data)} layers")
    print(f"  Contextual: {len(contextual_data)} layers")

    if not any([nn_data, logitlens_data, contextual_data]):
        print("\nWARNING: No Qwen2-VL data available yet.")
        print("Results are still being generated by run_all_missing.sh")
        return

    # Create output directory
    OUTPUT_DIR.mkdir(parents=True, exist_ok=True)

    # Unified plot
    if not args.individual_only:
        print("\nGenerating unified plot...")
        fig = create_unified_plot(nn_data, logitlens_data, contextual_data)
        for ext in ['pdf', 'png']:
            output_file = OUTPUT_DIR / f'qwen2vl_unified.{ext}'
            fig.savefig(output_file, dpi=300, bbox_inches='tight')
            print(f"  ✓ Saved {output_file}")
        plt.close(fig)

    # Individual plots
    if not args.unified_only:
        print("\nGenerating individual plots...")
        individual_figs = create_individual_plots(nn_data, logitlens_data, contextual_data)
        for method_key, fig in individual_figs.items():
            for ext in ['pdf', 'png']:
                output_file = OUTPUT_DIR / f'qwen2vl_{method_key}.{ext}'
                fig.savefig(output_file, dpi=300, bbox_inches='tight')
            print(f"  ✓ Saved {method_key}")
            plt.close(fig)

    print(f"\n✓ All plots saved to {OUTPUT_DIR}/")


if __name__ == '__main__':
    main()
